name: Scrape Product Prices

on:
  schedule:
    - cron: "*/10 * * * *" # Runs at 21:10 UTC daily
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js API
        run: 'curl -X GET "https://track-n-buy.vercel.app/api/scrape" -H "Authorization: Bearer ${{ secrets.SCRAPE_API_KEY }}"'
