name: Scrape Product Prices

on:
  schedule:
    - cron: "10 21 * * *" # Runs every 6 hours (UTC)
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Call Next.js API
        run: curl -X GET "https://yourdomain.com/api/scrape"
